name: Update Pre-Signed Link

on:
  schedule:
    - cron: '0 */10 * * *' # Every 10 hours
  workflow_dispatch: # Allows manual run

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4 # Update to v4 if available

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4 # Update to v4 if available
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install Boto3
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      # Run the script to generate the pre-signed URL
      - name: Generate Pre-Signed URL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: |
          python generate_presigned_url.py

      # Commit and push the updated download_link.txt
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add download_link.txt
          git commit -m "Update download link"
          git push
